"
This exception is raised on executing a breakpoint.

""BreakPoint signal"" is called from ""Object>>break"".
"
Class {
	#name : #BreakPoint,
	#superclass : #Halt,
	#category : #'System-Tools'
}
